# Generated by Django 5.0 on 2024-01-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={},
        ),
    ]
