# Generated by Django 5.0 on 2024-01-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'permissions': [('can_access_attempt', 'can access attempt')]},
        ),
    ]
