# Generated by Django 5.0 on 2024-01-15 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.AlterField(
            model_name='response',
            name='attempt',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.attempt'),
        ),
        migrations.AlterField(
            model_name='response',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
    ]
