# Generated by Django 5.0 on 2024-01-16 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_attempt_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'permissions': [('access_attempt', 'can access attempt')]},
        ),
    ]
