# Generated by Django 5.0 on 2024-01-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_options_alter_response_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
