# Generated by Django 5.0 on 2024-01-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
